### ISSUE TITLE
rb_binary should work as the tool in a run_binary

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_ruby#14]
The runfiles produced by an `rb_binary` target ought to be self-contained, so that binary can be used as the tool in a subsequent action that uses a Ruby program to transform some input files into files under `bazel-out`.

I think this is currently not working, here's a PR with a demo that I'd expect to work:
https://github.com/p0deje/rules_ruby/pull/15

**Comment by p0deje** [comment]
Implemented in ##38
