### ISSUE TITLE
Allow custom directory structure

### ISSUE THREAD

**Issue by protocol7** [bazel-contrib/rules_ruby#146]
It seems like the ruleset requires the `lib` and `spec` directories to be at the root of the repository. We are looking at using the rules in a larger, mixed language monorepo where code typically lives in sub-directories based on the application name. In trying to adapt the `gem` example to fit our use case, we noted that the `lib` and `spec` directories are no longer available in the `LOAD_PATH` if these directories are not at the root. A simplified example can be found at: https://github.com/protocol7/rules_ruby/tree/subdirs/examples/gem

This uses a directory layout like:
```
├── BUILD
├── Gemfile
├── Gemfile.lock
├── MODULE.bazel
├── MODULE.bazel.lock
├── WORKSPACE.bzlmod
└── foo
    ├── lib
    │   ├── BUILD
    │   └── gem
    │       ├── BUILD
    │       └── add.rb
    └── spec
        ├── BUILD
        └── add_spec.rb
```

Is it possible to make the ruleset work for this type of use case?

**Comment by p0deje** [comment]
There is nothing in the ruleset that forces you to use `lib`/`spec` directories at the root. In fact, the Selenium project keeps all Ruby code under `rb/` directory, and everything works just fine. You can see the example here - https://github.com/SeleniumHQ/selenium/tree/trunk/rb.

Can you provide more details on the targets you try to run and what are the exact LOAD_PATH failures you see? Also, feel free to ask on #ruby channel in Bazel Slack - it might be faster to iterate on this issue there.

**Comment by protocol7** [comment]
Thanks for the quick response and the confirmation that the ruleset is agnostic to the directory structure. Indeep, in our case it turned out to be a rspec configuration issue. I'll close this.
