### ISSUE TITLE
Tech debt: CI bzlmod testing ignores ruby_version.bzl

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_ruby#23]
Currently the approach for testing different interpreters is for CI to `Run echo 'RUBY_VERSION = "3.1.4"' > ruby_version.bzl` but under MODULE.bazel this .bzl file cannot be load()ed, so we have a fixed interpreter version.

**Comment by p0deje** [comment]
Related to https://github.com/bazelbuild/bazel/issues/17880
