### ISSUE TITLE
Provide a hermetic bundle command

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_ruby#41]
Without installing any ruby stuff on my machine, I'd like to be able to edit the `Gemfile` and `Gemfile.lock` files in a correct way by running sth like `bazel run @ruby//:gem -- install rails`, without worrying about version skew with a different version of gem than Bazel will use.

**Comment by p0deje** [comment]
Gem is not used to install dependencies in Gemfile/Gemfile.lock. Instead, one should use the following:

```
bazel run @rules_ruby_dist//:bundle -- add rails
```

This doesn't work at the moment though, I'll fix it.

**Comment by p0deje** [comment]
I just tested and the following works:

```
$ bazel run @bundle//:bin/bundle -- add rails
# a lot of output with installing rails

$ git diff --stat
 examples/gem/Gemfile       |   2 ++
 examples/gem/Gemfile.lock  | 145 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 3 files changed, 147 insertions(+), 2 deletions(-)
```

I've seen issues doing this on JRuby, but it works fine on MRI.

**Comment by alexeagle** [comment]
That feels like a bootstrap issue, how would I get a `@bundle` external repo if I haven't installed anything yet? Does it mean I have to `touch Gemfile Gemfile.lock` first so there are empty files to include in an `rb_bundle()` repo rule?

**Comment by p0deje** [comment]
@alexeagle Yes, we should probably still expose `ruby/gem` commands. However, `gem` should only be used for bootstrapping - for everything else `bundle` is a proper choice.

**Comment by p0deje** [comment]
@alexeagle Are there any great examples of rulesets exposing interpreter binaries? In case of Ruby, we cannot simply export `bin/` directory because PATH/GEM_PATH (and potentially other variables) needs to be exported.

**Comment by RyanDraves** [comment]
> @alexeagle Are there any great examples of rulesets exposing interpreter binaries? In case of Ruby, we cannot simply export `bin/` directory because PATH/GEM_PATH (and potentially other variables) needs to be exported.

I don't have examples off-hand, but I've usually seen tools exposed exposed as `@module//<tool>_binary` or something similar.

#48 seems to have gotten rid of support for this `bin/` export, which is unfortunate because I was having success using a script that calls
```
bazel run @bundle//:bin/bundle -- $@
```
but that doesn't seem supported anymore.

For those following along and wanting the tool to be exposed, I got it working by digging for the target corresponding to the binary and wrapping it into a script to jump out of the sandbox:
```starlark
BUILD

sh_binary(
    name = "bundle",
    srcs = ["jump_script.sh"],
    # Version grabbed from `bazel query "@bundle//:*"`
    data = ["@bundle//:bundler-2.2.33"],
    args = ["$(locations @bundle//:bundler-2.2.33)"],
)
```

```bash
jump_script.sh

#!/bin/bash
# Grabs a hermetically installed tool and hops back into the workspace
# Borrowed from https://stackoverflow.com/a/72816931

set -e

LAUNCH_WORKING_DIRECTORY=$(pwd)

if test "${BUILD_WORKING_DIRECTORY+x}"; then
  cd $BUILD_WORKING_DIRECTORY
fi

# I can't figure out a way to deal with needing `$locations` over `$location`, so the final path is hardcoded + the number of arguments to skip (1 extra path) is hardcoded
$LAUNCH_WORKING_DIRECTORY/$1/bin/bundle "${@:3}"
```

which lets me know run (or wrap into a separate script) `bazel run //:bundle --`

**Comment by p0deje** [comment]
> https://github.com/bazel-contrib/rules_ruby/pull/48 seems to have gotten rid of support for this bin/ export, which is unfortunate because I was having success using a script that calls

Indeed it no longer works, though for a transition period, you could still use `rb_bundle(...)` which still behaves exactly as before. Eventually, I'll implement all the binstubs support. That's actually the first thing on my list.

> For those following along and wanting the tool to be exposed, I got it working by digging for the target corresponding to the binary and wrapping it into a script to jump out of the sandbox:

Thanks for sharing, I'll see if I could generalize this solution.

**Comment by p0deje** [comment]
I managed to have binaries for the toolchain (`@ruby`), it would look like this:

```
    bazel run @ruby//:bundle -- update           -> update gems in Gemfile.lock
    bazel run @ruby//:bundle -- add rails        -> add Rails gem to Gemfile
    bazel run @ruby//:gem -- install rails       -> install Rails gem to the toolchain
    bazel run @ruby//:rails -- new $(pwd)/my_app -> create Rails application to ./my_app directory
```

I'm yet to make binaries work for `@bundle` installations.
