### ISSUE TITLE
Long filepath issue on Windows

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_ruby#64]
A TODO for this was introduced in #48

https://github.com/bazel-contrib/rules_ruby/pull/48/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR48

Try removing the exclusion and see if there's a way to fix it.

**Comment by p0deje** [comment]
Related to https://github.com/jruby/jruby/issues/3995#issuecomment-2558240341

**Comment by p0deje** [comment]
It looks like an upstream issue, can be worked around on CI by using really short output_base like `D:/b`:

https://github.com/bazel-contrib/rules_ruby/blob/0a2d57b805640d9c4d141bec45dcefea3df39b44/.github/workflows/ci.yml#L67-L68
